apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-deployment
  labels:
    app: bill-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-app 
  template:
    metadata:
      labels:
        app: bill-app
    spec:
      containers:
        - name: bill-app
          image: uar2022/k8s:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: postgres-root-db-name
                  name: postgres-secret
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-root-username
                  name: postgres-secret
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-root-password
                  name: postgres-secret
          securityContext:
              privileged: false  
---
apiVersion: v1
kind: Service
metadata:
  name: bill-service
spec:
  selector:
    app: bill-app
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31111


    