apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    apps: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: postgres
  template:
    metadata:
      labels:
        apps: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          # env:
          #   - name: POSTGRES_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: postgres-secret
          #         key: POSTGRES_USER
          #   - name: POSTGRES_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: postgres-secret
          #         key: POSTGRES_PASSWORD
          #   - name: POSTGRES_DB
          #     valueFrom:
          #       secretKeyRef:
          #         name: postgres-configmap
          #         key: POSTGRES_DB

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    apps: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP





